### ISSUE TITLE
ipynb file unavailable

### ISSUE THREAD

**Issue by cooleel** [blaylockbk/pyBKB_v2#3]
Hello,
I can't open this file: pyBKB_v2/demos/Find_nearest_lat_lon_in_grid.ipynb.
Have tried on Chrome and IE, neither of them works.
Could you please take a look at it?
Thanks.

**Comment by blaylockbk** [comment]
Sometimes GitHub has trouble rendering jupyter notebooks. You can use the nbviewer instead...
http://nbviewer.jupyter.org/github/blaylockbk/pyBKB_v2/blob/master/demos/Find_nearest_lat_lon_in_grid.ipynb
